[package]
name = "matscan"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bson = "2.6.1"
anyhow = "1.0.72"
azalea-chat = { git = "https://github.com/mat-1/azalea", default-features = false }
default-net = "0.17.0"
dotenv = "0.15.0"
libc = "0.2.147"
perfect_rand = "0.1.5"
pnet = "0.34.0"
pnet_macros = "0.34.0"
pnet_macros_support = "0.34.0"
rand = "0.8.5"
regex = "1.9.3"
serde = "1.0.183"
serde_json = "1.0.104"
tokio = { version = "1.30.0", features = ["full"] }
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.17", features = ["env-filter"] }
futures-util = "0.3.28"
lru-cache = "0.1.2"
toml = "0.7.6"
reqwest = { version = "0.11.18", default-features = false, features = [
    "json",
    "rustls-tls",
] }
parking_lot = "0.12.1"
enum-utils = "0.1.2"
flate2 = "1.0.26"
async-trait = "0.1.73"
mongodb = "2.6.0"

[dev-dependencies]
criterion = { version = "0.5.1", features = ["html_reports"] }

# [profile.release]
# debug = true

[features]
benchmark = []

[[bench]]
name = "my_benchmark"
harness = false
